name: 🚀 CD Pipeline

on:
  workflow_run:
    workflows: ["🔄 CI Pipeline"]
    types:
      - completed
    branches:
      - main  # ✅ Runs only when CI succeeds on the main branch

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # ✅ Only runs if CI passed

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build and Push Docker Images
        run: |
          echo "🐳 Building frontend image..."
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-frontend:${{ github.sha }} .

          echo "🐳 Building MySQL image..."
          docker build -f Dockerfile.mysql -t ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-database:${{ github.sha }} .

          echo "📤 Pushing frontend image..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-frontend:${{ github.sha }}

          echo "📤 Pushing MySQL image..."
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-database:${{ github.sha }}

      - name: 🚀 Simulate Deployment
        run: |
          echo "🧪 Simulating deployment..."
          echo "✅ Docker images deployed to server (simulated)"
          echo "Frontend: ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-frontend:${{ github.sha }}"
          echo "Database: ${{ secrets.DOCKERHUB_USERNAME }}/ukshati-database:${{ github.sha }}"

      - name: 📢 Notify Success
        if: success()
        run: echo "🎉 Deployment completed successfully!"

      - name: 📢 Notify Failure
        if: failure()
        run: echo "❌ Deployment failed!"
