name: 🔄 CI Pipeline

on:
  push:
    branches: [github-actions]
  pull_request:
    branches: [github-actions]

env:
  NODE_VERSION: '20'

jobs:
  test-build:
    name: 🧪 Test & Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: company_db
          MYSQL_USER: company
          MYSQL_PASSWORD: Ukshati@123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: 📦 Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: 🔍 Linting and Code Quality Check
        working-directory: ./frontend
        run: |
          echo "Running ESLint..."
          npm run lint:ci
          echo "✅ Linting and code quality check completed"

      - name: 🧪 Run Unit Tests
        working-directory: ./frontend
        run: npm run test:unit

      - name: 🧪 Run Integration Tests
        working-directory: ./frontend
        run: npm run test:integration

      - name: 🏗️ Build Application
        working-directory: ./frontend
        run: npm run build

      - name: 🔐 Security Scans
        working-directory: ./frontend
        run: |
          echo "Running security audit..."
          npm audit --audit-level=critical || echo "Non-critical vulnerabilities found, continuing..."